// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using CFAPI.Models;

#nullable disable

namespace CFAPI.Migrations
{
    [DbContext(typeof(CompanyContextCF))]
    [Migration("20230510055007_CreateDB")]
    partial class CreateDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CFAPI.Models.Dept", b =>
                {
                    b.Property<int>("Deptno")
                        .HasColumnType("int");

                    b.Property<string>("Ename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Deptno");

                    b.ToTable("Depts");
                });

            modelBuilder.Entity("CFAPI.Models.Emp", b =>
                {
                    b.Property<int>("EmpNo")
                        .HasColumnType("int");

                    b.Property<int?>("DeptnavDeptno")
                        .HasColumnType("int");

                    b.Property<string>("EName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("deptno")
                        .HasColumnType("int");

                    b.HasKey("EmpNo");

                    b.HasIndex("DeptnavDeptno");

                    b.ToTable("emps");
                });

            modelBuilder.Entity("CFAPI.Models.Emp", b =>
                {
                    b.HasOne("Rel2CodeFirst.Models.Dept", "Deptnav")
                        .WithMany("Emps")
                        .HasForeignKey("DeptnavDeptno");

                    b.Navigation("Deptnav");
                });

            modelBuilder.Entity("CFAPI.Models.Dept", b =>
                {
                    b.Navigation("Emps");
                });
#pragma warning restore 612, 618
        }
    }
}
